spring:
  profiles:
    active: 
      - dev
---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka-client
eureka:
  instance:
    hostname: erueka7001.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false       #false表示自己就是注册中心，负责维护服务实例，并不需要检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001
spring:
  profiles: test
  application:
    name: springcloud-config-eureka-client
eureka:
  instance:
    hostname: erueka7001.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false       #false表示自己就是注册中心，负责维护服务实例，并不需要检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/